### PR TITLE
Fix calc of coordinator output cost, give max available on change outputs

### LINKED ISSUE #126: Still overpaying on fees

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #126

### CODE REVIEW

**Comment by benthecarman** [comment]
To do, move input & output fee calculations to core

File: server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala [hunk 1]
```diff
@@ -85,14 +85,16 @@ case class VortexCoordinator(bitcoind: BitcoindRpcClient)(implicit
...
 
-  private[coordinator] def outputFee: CurrencyUnit = {
+  private[coordinator] def outputFee(
+      feeRate: SatoshisPerVirtualByte = feeRate,
+      numPeers: Int = config.minPeers): CurrencyUnit = {
     val outputSize = getScriptTypeOutputSize(config.outputScriptType)
 
-    val coordinatorOutputSize = getScriptTypeInputSize(config.changeScriptType)
+    val coordinatorOutputSize = getScriptTypeOutputSize(config.changeScriptType)
     val txOverhead = 10
```
Comment (benthecarman) [inline server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala:94]: Bump to 12
